In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

In [6]:
df1 = pd.read_csv("train.csv")
df1.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [7]:
df2 = df1.drop(columns=["ID", "age_desc","relation","ethnicity","contry_of_res",'age'])

In [8]:
print(df2['gender'].unique())
df2['gender'] = df2['gender'].replace({
    'f': 1, 'female': 1,
    'm': 0, 'male': 0
})
df2['jaundice'] = df2['jaundice'].replace({
    'yes': 1, 
    'no': 0
})
df2['austim'] = df2['austim'].replace({
    'yes': 1, 
    'no': 0
})
df2['used_app_before'] = df2['used_app_before'].replace({
    'yes': 1, 
    'no': 0
})

['f' 'm']

C:\Users\nehar\AppData\Local\Temp\ipykernel_9500\763957283.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['gender'] = df2['gender'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_9500\763957283.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['jaundice'] = df2['jaundice'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_9500\763957283.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['austim'] = df2['austim'].replace({
C:\Users\nehar\AppData\Local\Temp\ipykernel_9500\763957283.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['used_app_before'] = df2['used_app_before'].replace({

In [9]:
X= df2.drop('Class/ASD',axis='columns')
X

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,gender,jaundice,austim,used_app_before,result
0,1,0,1,0,1,0,1,0,1,1,1,0,0,0,6.351166
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2.255185
2,1,1,1,1,1,1,1,1,1,1,0,0,1,0,14.851484
3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.276617
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-4.777286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0,1,0,0,0,0,0,0,1,1,0,0,0,0,12.999501
796,0,1,1,0,0,1,0,1,1,1,0,0,0,0,13.561518
797,0,0,0,0,0,0,0,0,0,0,0,1,0,0,2.653177
798,0,0,0,0,0,0,0,0,0,0,1,0,0,0,9.069342
799,0,1,0,0,0,0,0,0,0,0,1,0,0,1,2.243304

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [16]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X, y)
model.score(X,y)

1.0